[project]
name = "volatilityanalysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "arch>=7.0",
    "matplotlib>=3.8",
    "numpy>=1.26",
    "pandas>=2.1",
    "pytest>=8.0",
    "scipy>=1.11",
    "statsmodels>=0.14",
]

[project.scripts]
volatilityanalysis = "volatilityanalysis:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
